AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create secrets

Resources:
  secretAuthorizationMinMambu:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Secreto que almacena las credenciales para conectarse con Minmambu en la cuenta de Multiprojects
      Name: scm-pasivos-dev-secretAuthMinMambu
      SecretString: '{"client_id": "to_change", "client_secret": "to_change", "resource" : "to_change", "grant_type" : "to_change", "token_type" : "to_change"}'      
      Tags: 
        - Key: Name
          Value: scm-pasivos-dev-secretAuthMinMambu

  secretAuthorizationMinMambuSSO:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Secreto que almacena el secreto para autenticar Minmambu con el SSO
      Name: scm-pasivos-dev-secretAuthorizationMinMambuSSO
      SecretString: '{"tenantID": "to_change", "clientID": "to_change", "scopes" : "to_change", "resource" : "to_change", "secret" : "to_change"}'    
      Tags: 
        - Key: Name
          Value: scm-pasivos-dev-secretAuthorizationMinMambuSSO
